on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # precisa disso para ver as tags!

      - name: Get latest tag
        id: get_tag
        shell: bash
        run: |
          TAGS=$(git tag --list 'v*' --sort=-v:refname)
          LATEST_TAG=$(echo "$TAGS" | awk 'NR==1')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          LATEST_TAG="${{ steps.get_tag.outputs.latest_tag }}"
          if [[ -z "$LATEST_TAG" ]]; then
            LOG=$(git log --pretty=format:"- %s (%h)" )
          else
            LOG=$(git log "${LATEST_TAG}..HEAD" --pretty=format:"- %s (%h)")
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
